<?php
 $aik =  array (
  'sitename' => '掩耳影院',
  'pcdomain' => 'http://mv.covear.top',
  'title' => '掩耳影院',
  'keywords' => 'CovEar, 掩耳, 影院, 免费, VIP, 破解, 电影, ',
  'description' => '免VIP抢先观看最新好看的电影和电视剧',
  'icp' => '湘ICP备17019987号',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传<br />若本站收录的节目无意侵犯了贵司版权，请给网页底部邮箱地址来信,我们会及时处理和回复,谢谢。',
  'tongji' => '',
  'hometopnotice' => '',
  'path' => '/',
  'mobiledomain' => '',
  'jiekou1' => 'http://api.baiyug.cn/vip/index.php?url=',
  'jiekou2' => 'https://api.47ks.com/webcloud/?v=',
  'jiekou3' => 'https://api.flvsp.com/?url=',
  'jiekou4' => 'http://api.xfsub.com/index.php?url=',
  'jiekou5' => 'http://api.nepian.com/ckparse/?url=',
  'jiekou6' => 'http://aikan-tv.com/?url=',
  'jiekou7' => 'http://jiexi.92fz.cn/player/vip.php?url=',
  'jiekou8' => 'http://jx.10087.tv/bdy/mf.php?vid=',
  'jiekou9' => 'http://j.zz22x.com/jx/?url=',
  'jiekou10' => 'http://api.662820.com/xnflv/index.php?url=',
  'admin_name' => 'admin',
  'admin_pass' => 'fedbb62b753edbe741082a30433b46cc',
  'admin_email' => 'i@i.covear.top',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '',
  'tv_ad' => '',
  'zongyi_ad' => '',
  'dongman_ad' => '',
  'jiazai_ad' => '',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian1_ad' => '',
  'cebian3_ad' => '',
  'weixin_ad' => '',
  'end_ad' => '',
  'hometopright' => '',
  'homelink' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>